require 'rbconfig'
# ruby 1.8.7 doesn't define RUBY_ENGINE
ruby_engine = defined?(RUBY_ENGINE) ? RUBY_ENGINE : 'ruby'
ruby_version = RbConfig::CONFIG["ruby_version"]
path = File.expand_path('..', __FILE__)
$:.unshift "#{path}/"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/hashie-3.5.6/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/confstruct-1.0.2/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-configure-0.1.2.5/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/naught-1.1.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/thread_safe-0.3.6/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/tzinfo-1.2.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-clock-0.4.0.7/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-attribute-0.1.3.5/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-initializer-0.1.0.2/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-subst_attr-0.1.0.2/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-dependency-0.1.0.4/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-telemetry-0.3.1.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/terminal_colors-0.0.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-log-0.4.3.5/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-cycle-0.3.0.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-async_invocation-0.1.0.4/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-casing-0.3.0.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-identifier-uuid-0.1.1.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-set_attributes-0.3.0.2/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-validate-0.3.1.5/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-virtual-0.1.0.2/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-schema-0.6.1.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-transform-0.1.2.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-message_store-0.2.1.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-messaging-0.18.1.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/ntl-actor-1.2.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/ntl-actor-1.2.3/src"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-consumer-0.5.0.4/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-settings-0.2.0.5/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/extensions/x86_64-darwin-14/2.4.0-static/pg-0.21.0"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/pg-0.21.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-message_store-postgres-0.3.0.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-messaging-postgres-0.7.0.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-consumer-postgres-0.2.0.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-entity_cache-0.15.0.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-entity_projection-0.3.0.3/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-entity_store-0.5.0.0/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-entity_snapshot-postgres-0.2.1.1/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/eventide-postgres-0.2.0.2/lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/evt-component_host-0.1.0.3/lib"
$:.unshift "#{path}/../../lib"
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/test_bench-1.3.4/lib"
